<a href="https://colab.research.google.com/github/Alister-Clietus/LEARN.PY/blob/main/TASK_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [1]:
#please provide your answer below this line.
import numpy as np
arr_1=np.random.randint(10,high=99,size=64).reshape(8,8)
print(arr_1)

[[96 62 38 45 59 90 11 40]
 [24 63 28 33 15 42 39 41]
 [92 56 24 19 91 78 30 52]
 [81 25 69 30 82 33 52 19]
 [12 13 53 26 10 69 90 31]
 [98 82 76 32 70 54 44 77]
 [51 16 21 34 29 96 21 13]
 [76 92 38 50 91 32 45 84]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [7]:
#please provide your answer below this line.
import numpy as np
arr_1=np.linspace(10,99,16).reshape(4,4)
print(arr_1)
print(" ")
arr_2=arr_1.reshape(2,8)
arr_3=np.vstack(arr_2)
print(arr_3)
print(" ")
arr_4=arr_1.reshape(8,2)
arr_5=np.hstack(arr_4)
print(arr_5)


[[10.         15.93333333 21.86666667 27.8       ]
 [33.73333333 39.66666667 45.6        51.53333333]
 [57.46666667 63.4        69.33333333 75.26666667]
 [81.2        87.13333333 93.06666667 99.        ]]
 
[[10.         15.93333333 21.86666667 27.8        33.73333333 39.66666667
  45.6        51.53333333]
 [57.46666667 63.4        69.33333333 75.26666667 81.2        87.13333333
  93.06666667 99.        ]]
 
[10.         15.93333333 21.86666667 27.8        33.73333333 39.66666667
 45.6        51.53333333 57.46666667 63.4        69.33333333 75.26666667
 81.2        87.13333333 93.06666667 99.        ]
