<a href="https://colab.research.google.com/github/Alister-Clietus/LEARN.PY/blob/main/TASK_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate two  3 x 3 matrix and find it's dot product and take the transpose of the answer.

In [5]:
#please provide your answer below this line.
import numpy as np
arr_1=np.arange(9).reshape(3,3)
arr_2=np.arange(9).reshape(3,3)
arr_3=np.dot(arr_1,arr_2)
print("Dot Product Of Matrix is",arr_3)
arr_3_transpose=arr_3.transpose()
print("Transpose OF Answer is",arr_3_transpose)

Dot Product Of Matrix is [[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]
Transpose OF Answer is [[ 15  42  69]
 [ 18  54  90]
 [ 21  66 111]]


2. Create a 3x3 matrix with elements [55,25,15], [30,44,2], [11,45,77] . Now find the determinant of the given matrix.

In [7]:
#please provide your answer below this line.
import numpy as np
arr_1=np.array([[55,25,15], [30,44,2], [11,45,77]]).reshape(3,3)
print("Given Array is \n",arr_1)
dt=np.linalg.det(arr_1)
print("Determinant Of Given Matrix is ",dt) 



Given Array is 
 [[55 25 15]
 [30 44  2]
 [11 45 77]]
Determinant Of Given Matrix is  137180.0000000001
