<a href="https://colab.research.google.com/github/Alister-Clietus/LEARN.PY/blob/main/TASK_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

N.B: Please find the answers by applying the functions on the matrices

1. Create 2 3×3 matrix with 0-8 and 10-19 as elements in each and perform the vectorize multiplication operations on the matrices.(Outer product, Dot product, Element wise product).

In [6]:
#please type your answer below this line.
import numpy as np
arr_1=np.arange(9).reshape(3,3)
print("First Array\n",arr_1)
arr_2=np.arange(10,19).reshape(3,3)
print("Second Array\n",arr_2)
print("Outer Product\n",np.outer(arr_1,arr_2))
print("Dot Product\n",np.dot(arr_1,arr_2))
print("Element Wise Product\n",np.multiply(arr_1,arr_2))




First Array
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Second Array
 [[10 11 12]
 [13 14 15]
 [16 17 18]]
Outer Product
 [[  0   0   0   0   0   0   0   0   0]
 [ 10  11  12  13  14  15  16  17  18]
 [ 20  22  24  26  28  30  32  34  36]
 [ 30  33  36  39  42  45  48  51  54]
 [ 40  44  48  52  56  60  64  68  72]
 [ 50  55  60  65  70  75  80  85  90]
 [ 60  66  72  78  84  90  96 102 108]
 [ 70  77  84  91  98 105 112 119 126]
 [ 80  88  96 104 112 120 128 136 144]]
Dot Product
 [[ 45  48  51]
 [162 174 186]
 [279 300 321]]
Element Wise Product
 [[  0  11  24]
 [ 39  56  75]
 [ 96 119 144]]


2. Create a 4×4 matrix with 0-16  as elements in it. Add a scalar 4 to the matrix and also multiply it with [1,2,3,4] 1-D matrix by broadcasting. ( Please note to do both the addition and multiplication by broadcasting.)

In [9]:
#please type your answer below this line.
import numpy as np
arr_1=np.arange(16).reshape(4,4)
print("First Array\n",arr_1)
arr_2=arr_1+4
print("Scalar 4 added matrix\n",arr_2)
arr_mul=[1,2,3,4]
arr_3=arr_1*arr_mul
print("MultiplIY wITH [1,2,3,4] matrix\n",arr_3)


First Array
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Scalar 4 added matrix
 [[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
MultiplIY wITH [1,2,3,4] matrix
 [[ 0  2  6 12]
 [ 4 10 18 28]
 [ 8 18 30 44]
 [12 26 42 60]]
