<a href="https://colab.research.google.com/github/Alister-Clietus/LEARN.PY/blob/main/TASK_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create an 4x4 array containing the values ranging from 0 - 15 (use arange function). Then ,
  
  a) split it equally along horizontal.

  b) split it as 4 parts vertically.



In [4]:
#please provide your answer below this line
import numpy as numpy1
arr_1=numpy1.arange(16).reshape(4,4)
print(arr_1)
print(numpy1.hsplit(arr_1,4))
print(numpy1.vsplit(arr_1,4))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0],
       [ 4],
       [ 8],
       [12]]), array([[ 1],
       [ 5],
       [ 9],
       [13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


2. Create a 3x3 matrix using random module and then,

  a) Find the ceil of the matrix.
  
  b) Find the floor of the matrix.

In [10]:
#please provide your answer below this line
import numpy as np
arr_1=np.random.randint(10,high=15,size=9).reshape(3,3)
print("Given Matrix is\n",arr_1)
arr_ceil=np.ceil(arr_1)
print("Given Ceil Of The Matrix Is\n",arr_ceil)
arr_floor=np.floor(arr_1)
print("Given Ceil Of The Matrix Is\n",arr_floor)

Given Matrix is
 [[10 13 14]
 [13 11 13]
 [10 10 10]]
Given Ceil Of The Matrix Is
 [[10. 13. 14.]
 [13. 11. 13.]
 [10. 10. 10.]]
Given Ceil Of The Matrix Is
 [[10. 13. 14.]
 [13. 11. 13.]
 [10. 10. 10.]]


3. Create a random 1x4 array and print the random array and its shape.
    
      (use the shape function for finding the shape & use the same random we created here for both the below operations.)

  a) Squeeze the random array and print the squeezed array and its shape.
  b) Expand the random array by one axis and print the expanded array and its shape.

In [39]:
#please provide your answer below this line.
import numpy as np
arr_1=np.random.randint(10,high=14,size=4).reshape(2,2,1)
print("Shape Of The array is",np.shape(arr_1))
print("The array is",arr_1)
print("Shpe Of Squeezed Aray is",np.squeeze(arr_1,axis=2).shape)
print("Squeezed Aray is",np.squeeze(arr_1,axis=2))
print("Shape Of Expanded Array is ",np.expand_dims(arr_1, axis=0).shape)
print("Expanded Array is ",np.expand_dims(arr_1, axis=0))





Shape Of The array is (2, 2, 1)
The array is [[[11]
  [10]]

 [[10]
  [11]]]
Shpe Of Squeezed Aray is (2, 2)
Squeezed Aray is [[11 10]
 [10 11]]
Shape Of Expanded Array is  (1, 2, 2, 1)
Expanded Array is  [[[[11]
   [10]]

  [[10]
   [11]]]]
